### ISSUE TITLE
Cloud Run issues logging to Stackdriver

### ISSUE THREAD

**Issue by michaelsatanovsky** [cloudprober/cloudprober#257]
I am now able to run Cloudprober on Cloud Run. However, I occasionally run into an issue when writing to Stackdriver.

When the instance first starts up, I get `"Error getting instance name on GCE, using HOSTNAME environment variable: metadata: GCE metadata "instance/name" not defined"`

Later, upon every logging instance, I get `Unable to fulfill TimeSeries Create call. Err: googleapi: Error 400: One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: gce_instance{zone:us-east1-1,instance_id:} timeSeries[0-13]: custom.googleapis.com/cloudprober/sysvars/sysvars/instance{val:}`

I get the first error every time, but I get the second error 75% of the time. On the instances that do have that error, nothing is logged in Stackdriver.

Let me know if there's any other information I should provide!

**Comment by manugarg** [comment]
I think the first error is okay; we can convert it to a warning if that helps.

Regarding the second issue.. timeseries not being in order,  I am wondering if you are running multiple instances and not having instance id in the timeseries call is mixing up the timeseries in stackdriver (i.e. stackdriver doesn't have a way to different timeseries from one instance from another).

**Comment by michaelsatanovsky** [comment]
For the first error, it's already surfacing as a warning, so not a big deal. I was just adding some context if it was needed.

I just verified that I am not running multiple instances at once. Here was my process:

1. I had an instance running, but it was failing to log to Stackdriver with the above error.
2. I stopped that instance.
3. I started a new instance.
4. This new instance ran as desired. No issues. Logging to Stackdriver with no issues.
5. I stopped the new instance.
6. I waited five minutes and started a new instance.
7. This new instance is failing to log to Stackdriver with the above error.

**Comment by manugarg** [comment]
Thanks for the additional context @michaelsatanovsky!

So one thing is clear from the logs that instance_id is empty on these timeseries entries. That's not a good thing. We should fix that. Also, possibly, we need a different resource type for cloud run instances: https://github.com/cloudprober/cloudprober/blob/a1079cc9570e18bd709755841ab71b9b339ba568/surfacers/stackdriver/resource.go#L66

I'll try to find if there is a specific type for CloudRun.

**Comment by michaelsatanovsky** [comment]
Great, thanks Manu! Let me know if there's anything I can do to help.

**Comment by manugarg** [comment]
I've just now submitted an improvement (#258) and built a docker image with it. Can you please give it another try (with docker image tag - 'master') whenever you get a chance?

**Comment by michaelsatanovsky** [comment]
Seems like I'm still getting the same issue. 

Another piece of information which may be pertinent is that my probes seem to always be the same (see the attached image). I feel like the numbers (22 and 14) should change with every probe.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/10731760/216103356-212598ef-552d-4b47-b748-9c08d55ee5e1.png">

**Comment by manugarg** [comment]
Actually that 22 and 14 will not change. That's the count of timeseries in the cache. Every export cycle, that count will be same.

Can you share the full error log line again. I'd like to see the error message from Stackdriver (looking for the fields like type and job name).

**Comment by manugarg** [comment]
Another thing we can try is to add the following config to the surfacer:
https://github.com/cloudprober/cloudprober/blob/master/surfacers/proto/config.proto#L63-L66

```
surfacer {
  type: STACKDRIVER
   ...
  ignore_metrics_with_label {
     key: "probe",
     value: "sysvars",
   }
}
```

**Comment by michaelsatanovsky** [comment]
I will try to add that config.

Here's the full error log:

```
Unable to fulfill TimeSeries Create call. Err: googleapi: Error 400: One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: gce_instance{instance_id:,zone:us-east1-1} timeSeries[0-21]: custom.googleapis.com/cloudprober/sysvars/sysvars/start_timestamp{val:1675268190}
Details:
[
  {
    "@type": "type.googleapis.com/google.monitoring.v3.CreateTimeSeriesSummary",
    "errors": [
      {
        "pointCount": 12,
        "status": {
          "code": 3
        }
      }
    ],
    "successPointCount": 10,
    "totalPointCount": 22
  }
]
, badRequest
```

**Comment by manugarg** [comment]
@michaelsatanovsky it looks like the old docker image. Maybe Cloud Run has not refreshed the image because tag was not changing? For example, k8s re-pulls image by default only if it has tag "latest".

Can you try the image with the "main" tag? Both "master" and "main" point to the same image. Also, if there is a way to force Cloud Run to re-download image.

**Comment by michaelsatanovsky** [comment]
Hmm, I manually pulled "master" using docker. Will try again though.

**Comment by manugarg** [comment]
Try with the "main" tag. You can print the detailed cloudprober version like this, to verify:
```
09:25:48 ~/lft/otter/monitoring/cloudprober(k8s:ops-cluster)(git:cloudprober)$ docker run cloudprober/cloudprober:master --version
v0.12.2-7-g8230eb9
09:26:26 ~/lft/otter/monitoring/cloudprober(k8s:ops-cluster)(git:cloudprober)$ docker run cloudprober/cloudprober:main --version

Unable to find image 'cloudprober/cloudprober:main' locally
main: Pulling from cloudprober/cloudprober
a9eaa45ef418: Already exists
091c1d447e97: Pull complete
593addd4c70a: Pull complete
Digest: sha256:f38397d0598dc370c77dc43241e21da360e3ea65449e08d8f4393328ea01f529
Status: Downloaded newer image for cloudprober/cloudprober:main
v0.12.2-29-g2eda9f5
```

I think both .. new image and the config stanza above should provide useful clue.

**Comment by michaelsatanovsky** [comment]
The version I get for both "main" and "master" is: v0.12.2-29-g2eda9f5. Still getting the same results when running on Cloud Run:

```
Unable to fulfill TimeSeries Create call. Err: googleapi: Error 400: One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: gce_instance{zone:us-east1-1,instance_id:} timeSeries[0-7]: custom.googleapis.com/cloudprober/http/kms-encrypt/total{dst:cloudkms.googleapis.com}
Details:
[
  {
    "@type": "type.googleapis.com/google.monitoring.v3.CreateTimeSeriesSummary",
    "errors": [
      {
        "pointCount": 7,
        "status": {
          "code": 3
        }
      }
    ],
    "successPointCount": 1,
    "totalPointCount": 8
  }
]
, badRequest
```

**Comment by manugarg** [comment]
Thanks for trying it again. What's weird is that it's not using the new monitored resource I added. It's still showing the timeseries with gce_instance resource type. It shows that Cloud Run is not keeping the [contract](https://cloud.google.com/run/docs/container-contract#jobs-env-vars) of setting the CLOUD_RUN_JOB environment variable (that's what we use to determine if we should use cloud run specific monitored resource - see [here](https://github.com/cloudprober/cloudprober/blob/2eda9f5a0457815235aae38264c917a91b0a98a8/common/metadata/metadata.go#L43)), or something else is missing.

Can you please share a few more things:
1. How are you running Cloudprober on Cloud Run? As a Cloud Run job or as a service? Maybe I am looking for the wrong variable.
2. Cloudprober showed its version on its status page (port 9313). It looks like the following screenshot:

    <img width="768" alt="image" src="https://user-images.githubusercontent.com/1286425/216140391-3f5ce230-5b06-4308-aca4-e879891153de.png">
    
    Any chance you can access that for a Cloud Run job?

**Comment by michaelsatanovsky** [comment]
1. I've been running as a Cloud Run service. Perhaps I should have clarified that earlier.
2. This is the message I get on startup, hopefully what you are looking for: 
```
1675279135 labels=ptype=sysvars,probe=sysvars hostname="localhost" instance="" instance_id="00f8b6bdb896879fd4790ca59b2a79afc7423070529f1035fb9e4edc0c2b983f1a3682c0e085c98f14d9fdeabb63fa72bc47487e62b35a0f100eb06350cb2ff651" project="steam-way-362719" project_id="448213234141" start_timestamp="1675279135" version="v0.12.2-29-g2eda9f5"
```

**Comment by manugarg** [comment]
@michaelsatanovsky I've submitted one more change that should look for Cloud Run services as well. Whenever you get a chance can you please try the "main" image again. New cloudprober version should be: v0.12.2-30-ge7748ef.

**Comment by michaelsatanovsky** [comment]
Getting a different warning now (and still not getting metrics in Stackdriver):

```
Unable to fulfill TimeSeries Create call. Err: googleapi: Error 400: One or more TimeSeries could not be written: Metrics cannot be written to cloud_run_job. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_job. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_job. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_job. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_job. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_job. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_job. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.; Metrics cannot be written to cloud_run_job. See https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource for a list of writable resource types.
Details:
[
  {
    "@type": "type.googleapis.com/google.monitoring.v3.CreateTimeSeriesSummary",
    "errors": [
      {
        "pointCount": 8,
        "status": {
          "code": 3
        }
      }
    ],
    "totalPointCount": 8
  }
]
, badRequest
```

**Comment by manugarg** [comment]
Okay, this is a more useful error message. As per the [URL](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#md-create) in the error message, metrics cannot be written for cloud run jobs or services:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/1286425/216163708-4df43a47-4c69-4cf1-91df-48d4f4721c5b.png">

For Cloud Run custom metrics, we'll have to use generic_task resource type. I'll make that change.

**Comment by michaelsatanovsky** [comment]
Ah, but it was working before because it was labelled as a gce_instance. Interesting.

**Comment by manugarg** [comment]
yeah, it was not complaining about that, but at that the same time, it was not the right setup (we were sending empty instance id).

I've submitted the fix. Whenever you get a chance, give it another try. It should at least try to submit metrics as generic_task.

**Comment by michaelsatanovsky** [comment]
Looks like it is almost working.

Now the error is same format as above but the important part is: 
`Unable to fulfill TimeSeries Create call. Err: googleapi: Error 400: One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (namespace task_id).`

**Comment by manugarg** [comment]
Okay, so it wants all the labels to be set as well. I've just made that change. Let's give it another try :) Fingers crossed!

**Comment by michaelsatanovsky** [comment]
I was hopeful, but it seems like we're back to this:

```
Unable to fulfill TimeSeries Create call. Err: googleapi: Error 400: One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: generic_task{namespace:cloudprober,job:cp-test,location:us-east1,task_id:cp-test-00001-bep} timeSeries[0-7]: custom.googleapis.com/cloudprober/http/kms-encrypt/total{dst:cloudkms.googleapis.com}
Details:
[
  {
    "@type": "type.googleapis.com/google.monitoring.v3.CreateTimeSeriesSummary",
    "errors": [
      {
        "pointCount": 7,
        "status": {
          "code": 3
        }
      }
    ],
    "successPointCount": 1,
    "totalPointCount": 8
  }
]
, badRequest
```

**Comment by manugarg** [comment]
I kind of feared that. If it's okay, can you please share your cloudprober config (after redacting any confidential stuff of course).

**Comment by manugarg** [comment]
So I signed for the Cloud Run trial and tried to replicate the whole thing. I was able to write to stackdriver without any errors.

Computed failure ratio:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1286425/216261767-a31a6dff-f006-47c4-8e84-40be7123163d.png">

I wonder if something else is going on in this project. Looking at the config will help too.

**Comment by manugarg** [comment]
In fact, I tried running it twice to see if error shows up only if you restart. No error this time too (you can see on revision ending, another starting):
<img width="792" alt="image" src="https://user-images.githubusercontent.com/1286425/216262954-27f21d69-955c-4c74-a8d3-eb691a1ea906.png">

**Comment by michaelsatanovsky** [comment]
Here's my config file:

```
probe {
  name: "kms-encrypt"
  type: HTTP
  targets {
    host_names: "cloudkms.googleapis.com"
  }
  http_probe {
    relative_url: "XXXXXXXXX"
    protocol: HTTPS
    method: POST
    headers {
      name: "content-type"
      value: "application/json"
    }
    body: "{\"plaintext\": \"VGVzdAo=\"}"  # echo "Test" | base64
    oauth_config {
      google_credentials {
      }
    }
  }
  interval_msec: 30000
  timeout_msec: 1000
  validator {
    name: "status_code_200"
    http_validator {
      success_status_codes: "200"
    }
  }
  # Values for unit, name, and distributions are consistent with the EKM
  # latencies metric. Keep these the same as the decrypt() probe (below).
  latency_unit: "ms"
  latency_metric_name: "latencies"
  latency_distribution: {
    exponential_buckets: {
      scale_factor: 1.0
      base: 1.4
      num_buckets: 35
    }
  }
}
probe {
  name: "kms-decrypt"
  type: HTTP
  targets {
    host_names: "cloudkms.googleapis.com"
  }
  http_probe {
    relative_url: "XXXXXXXXXXX"
    protocol: HTTPS
    method: POST
    headers {
      name: "content-type"
      value: "application/json"
    }
    body: "{\"ciphertext\": XXXXXXXXXX}"
    oauth_config {
      google_credentials {
      }
    }
  }
  interval_msec: 30000
  timeout_msec: 1000
  validator {
    name: "plaintext"
    regex: "XXXXXXX"
  }
  # Keep this the same as the encrypt() probe (above).
  latency_unit: "ms"
  latency_metric_name: "latencies"
  latency_distribution: {
    exponential_buckets: {
      scale_factor: 1.0
      base: 1.4
      num_buckets: 35
    }
  }
}

# server {
#   type: HTTP
#   http_server {
#     port: 8080
#     pattern_data_handler {
#       response_size: 2
#       pattern: "ok"
#     }
#     pattern_data_handler {
#       response_size: 3
#       pattern: "200"
#     }
#   }
# }

# server {
#   type: HTTP
#   http_server {
#     port: 10402
#     pattern_data_handler {
#       response_size: 2
#       pattern: "ok"
#     }
#     pattern_data_handler {
#       response_size: 3
#       pattern: "200"
#     }
#   }
# }

surfacer {
  type: STACKDRIVER
  ignore_metrics_with_label {
     key: "probe",
     value: "sysvars",
   }
}
```

**Comment by manugarg** [comment]
Thanks for the config @michaelsatanovsky! I tried my config with validators and distributors..I was unable to reproduce the issue.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/1286425/216382907-b019423f-6de2-4cf9-9c37-97af39bdb9cd.png">

Also, I checked in the logs as well, there are no errors while sending the metrics to stackdriver:
..
```
2023-02-02 08:28:07.310 PST
Sending entries 0 through 6 of 6

{
  insertId: "1nntkfafcdzmph"
  logName: "projects/lasdada/logs/cloudprober.stackdriver"
  receiveTimestamp: "2023-02-02T16:28:09.228129291Z"
  resource: {2}
  severity: "INFO"
  textPayload: "Sending entries 0 through 6 of 6"
  timestamp: "2023-02-02T16:28:07.310223057Z"
}
```

I am not sure what's going on in your project to cause the rejections :(

**Comment by michaelsatanovsky** [comment]
I've been looking into it some more. I separated the two probes I have into their own Cloud Run instances, and the `kms-encrypt` probe seems to work fine, while the `kms-decrypt` probe is unable to log. 

When I run the encrypt instance first followed by decrypt, encrypt logs but decrypt does not. 
When I run decrypt first followed by encrypt, neither logs.

Unsure what this means, but still looking into it.

**Comment by manugarg** [comment]
While you're playing with it, you can also try changing the names of the probes, or the monitoring URL:
https://github.com/cloudprober/cloudprober/blob/d1b4071e8cc59764b087b56498552ae67287867e/surfacers/stackdriver/proto/config.proto#L27

```
surfacer {
  ...
  stackdriver_surfacer {
    monitoring_url: custom.googleapis.com/cloudprober2/
  }
}
```

To see if it produces different results.

**Comment by michaelsatanovsky** [comment]
Using a different monitoring URL tentatively seems to be working. Is it possible to use two different monitoring URLs in one Cloudprober instance? E.g., if I put my two probes back into one instance, can they log using different URLs?

**Comment by manugarg** [comment]
I'm sorry, do they have TimeSeries error even if you run them in different services with different monitoring URL? I am assuming you already tried changing the probe name? I am curious about that because somehow it sounds like there is something else running in your project, that's also exporting metrics to stackdriver, and that's interfering with the whole thing (though using different monitoring URL should disambiguate the whole thing).

I wonder if we've encountered some bug in stackdriver with respect to label naming and stuff. Can you also try replacing "-" in probe name by "_"?

**Comment by manugarg** [comment]
If you see this: https://cloud.google.com/monitoring/api/v3/naming-conventions, stackdriver seems to encourage using "_".

**Comment by manugarg** [comment]
Yep, confirmed. I changed my probe name to contain "-" instead of "_", and I could reproduce the error:

> Unable to fulfill TimeSeries Create call. Err: googleapi: Error 400: One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: generic_task{job:cloudprober,task_id:cloudprober-00001-teh,location:us-central1,namespace:cloudprober} timeSeries[0-7]: custom.googleapis.com/cloudprober/http/http-aws/resp-code{code:200,dst:aws.amazon.com} Details: [ { "@type": "type.googleapis.com/google.monitoring.v3.CreateTimeSeriesSummary", "errors": [ { "pointCount": 8, "status": { "code": 3 } } ], "totalPointCount": 8 } ] , badRequest

@michaelsatanovsky Please change the probe names to replace "-" by "_" and run the whole thing again.

**Comment by manugarg** [comment]
I think my diagnosis was wrong. It has nothing to do with the metric or label name. Cloud Run does some weird things, at least in the short run. It leaves containers from previous instance running / somehow restart container one more time for whatever reason. I noticed this:
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/1286425/217181901-2106dc47-d1d3-4679-b559-42a4a5c3e032.png">

I started the service after a long gap, and the errors came write away, but it turned out there was another instance of Cloudprober running at that time.

One returning the stackdriver errors, and the one that got terminated by Cloudprober had the same task_id:
task_id:cloudprober-00001-huy (based on stackdriver log labels).. and the same task_id continued.

Thing is Cloud Run seems to start multiple instances.. maybe in response to status page access or something else and every time task_id is same:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/1286425/217183660-142b0e3b-1f9e-44ae-85f7-7b08a4d0a294.png">
In fact, it just keeps doing it. .. i.e. it keeps restarting the container, while keeping the task_id same.

This is the real cause of errors.

**Comment by manugarg** [comment]
I think it all stabilizes at some point, if I leave the service running long enough. Given all this I am not sure if Cloud Run is right platform for Cloudprober, but if you want we can use a random id as task id to separate out our metrics.

**Comment by manugarg** [comment]
I went ahead and implemented the random task-id (see #267), and here you can see multiple cloudprober containers running in parallel:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/1286425/217200230-d47a3809-1f11-440c-bb51-26d0dc616daa.png">

I think #267 should fix the problem.

**Comment by michaelsatanovsky** [comment]
Seems like it is working. Thanks so much for your continued effort!

**Comment by manugarg** [comment]
Cool. No problem!

I'll mark this closed for now and will cut a new release soon.
